### ISSUE TITLE
一个疑问，为什么很多查询都。。。

### ISSUE THREAD

**Issue by hulang** [medz/gbt2260#3]
身份证是：`440620196807271766`
查询出来是：广东省佛山市

但是使用`https://qq.ip138.com/idsearch/`查询

结果
发证地 | 广东省 佛山市 中山市
部分或全部现为 | 广东省 中山市 中山市

还有使用`https://www.haoshudi.com/shenfenzheng/`查询

首次签发地 | 广东省 佛山市 中山市
现所属地 | 广东省 中山市 中山市

我都。。555555555。。。。到底？
我百度查询了下：440600 确实是:佛山市
中山市 442000

**Comment by medz** [comment]
因为地区归属每年都有可能变动所导致的。比如中山市，以前就是佛山市的县级市。现在独立归省管理。

**Comment by hulang** [comment]
明白了。。。目前作者你提供的就是对的。。。
